import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {Navbar} from "@/components/navbar/nav";
import Footer from "@/components/footer/footer";
import Newsletter from "@/components/newsletter/letterbox";
import ThanksMessage from "@/components/thanks/thanksmessage";
import ChatBotOpenButton from "@/components/chatbot/chatbot-openButton";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/ui/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mrityunjay Tiwari",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="thin-scrollbar">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
        <Navbar />
        {children}
        <div id="modal-root" />
        <Toaster />
        <Newsletter />
        <ThanksMessage />
        <Footer />
        <ChatBotOpenButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
